<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>HTML Document</title>
</head>
<body>
    <h1>This is a simple HTML document</h1>
    <p>Generated by request-mirror</p>
</body>
</html>