<?php

it('returns HTML document', function () {
    $response = $this->get('/html');

    $response->assertOk()
        ->assertHeader('Content-Type', 'text/html; charset=UTF-8');

    expect($response->content())
        ->toContain('<!DOCTYPE html>')
        ->toContain('<title>HTML Document</title>')
        ->toContain('<h1>This is a simple HTML document</h1>')
        ->toContain('Generated by request-mirror');
});